#include "WindowsBackend.h"

#include <QFile>
#include <QDir>
#include <QTextStream>
#include <QProcess>

// Returns true if makensis is available on PATH (or common install locations)
static bool makensisAvailable()
{
    QProcess p;
    // Try PATH first
    p.start("makensis", {"/VERSION"});
    if (p.waitForFinished(5000) && p.exitCode() == 0) return true;

    // Windows common locations (when cross-compiling from macOS/Linux via PATH is unlikely)
    // On macOS: brew install makensis
    p.start("which", {"makensis"});
    p.waitForFinished(3000);
    return p.exitCode() == 0;
}

QStringList WindowsBackend::validate(const Manifest &m, const QString &projectDir) const
{
    Q_UNUSED(projectDir)
    QStringList issues = m.validate();

    if (!makensisAvailable())
        issues << "INFO: makensis not found — a .nsi script will be generated but not compiled. "
                  "Install: brew install makensis  (macOS/Linux)  or  https://nsis.sourceforge.io  (Windows)";

    return issues;
}

QString WindowsBackend::outputFilename(const Manifest &m) const
{
    // Return .exe if makensis can compile, otherwise .nsi script
    const QString base = QString("%1-%2-%3-win64-setup")
        .arg(m.app.publisher, m.app.name, m.app.version)
        .replace(' ', '_');
    return base + (makensisAvailable() ? ".exe" : ".nsi");
}

bool WindowsBackend::build(const Manifest   &m,
                            const QString    &projectDir,
                            const QString    &outputDir,
                            const ProgressFn &progress,
                            QString          *errOut)
{
    report(progress, 5,  "=== Windows Build Started ===");
    report(progress, 10, QString("Generating NSIS script for %1 %2...").arg(m.app.name, m.app.version));

    QDir().mkpath(outputDir);
    QString nsiPath = outputDir + "/" + outputFilename(m);

    QString script = generateNsiScript(m, projectDir);
    if (script.isEmpty()) {
        if (errOut) *errOut = "Failed to generate NSIS script.";
        return false;
    }

    QFile f(nsiPath);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        if (errOut) *errOut = QString("Cannot write: %1").arg(nsiPath);
        return false;
    }
    f.write(script.toUtf8());
    f.close();

    report(progress, 70, "  NSIS script: " + nsiPath);

    // Try to compile with makensis if available
    QProcess which;
    which.start("which", {"makensis"});
    which.waitForFinished(3000);
    if (which.exitCode() == 0) {
        report(progress, 75, "  Compiling with makensis...");
        QString exePath = outputDir + "/" + outputFilename(m).replace(".nsi", ".exe");
        if (compileMakensis(nsiPath, exePath)) {
            report(progress, 95, "  Installer: " + exePath);
        } else {
            report(progress, 90, "  WARN: makensis compile failed. NSIS script is available.");
        }
    } else {
        report(progress, 90, "  makensis not found — NSIS script generated for manual compile.");
        report(progress, 92, "  Install: brew install makensis  (macOS/Linux cross-compile)");
        report(progress, 94, "           or compile on Windows with NSIS 3.x");
    }

    report(progress, 100, "=== Windows Build Complete ===");
    return true;
}

QString WindowsBackend::generateNsiScript(const Manifest &m, const QString &projectDir) const
{
    Q_UNUSED(projectDir)
    QString installDir = m.defaultInstallDir("windows");
    QString s;
    QTextStream ts(&s);

    ts << "; Generated by Mcaster1InstallSystem\n";
    ts << "; App: " << m.app.name << " " << m.app.version << "\n\n";

    ts << "!include \"MUI2.nsh\"\n\n";
    ts << "Name \"" << m.app.name << "\"\n";
    ts << "OutFile \"" << m.app.publisher << "-" << m.app.name << "-" << m.app.version << "-win64-setup.exe\"\n";
    ts << "InstallDir \"" << installDir << "\"\n";
    ts << "RequestExecutionLevel admin\n\n";

    ts << "!define MUI_ABORTWARNING\n";
    ts << "!insertmacro MUI_PAGE_WELCOME\n";
    ts << "!insertmacro MUI_PAGE_COMPONENTS\n";
    ts << "!insertmacro MUI_PAGE_DIRECTORY\n";
    ts << "!insertmacro MUI_PAGE_INSTFILES\n";
    ts << "!insertmacro MUI_PAGE_FINISH\n";
    ts << "!insertmacro MUI_UNPAGE_CONFIRM\n";
    ts << "!insertmacro MUI_UNPAGE_INSTFILES\n";
    ts << "!insertmacro MUI_LANGUAGE \"English\"\n\n";

    ts << "VIProductVersion \"" << m.app.version << ".0\"\n";
    ts << "VIAddVersionKey \"ProductName\"    \"" << m.app.name      << "\"\n";
    ts << "VIAddVersionKey \"CompanyName\"    \"" << m.app.publisher  << "\"\n";
    ts << "VIAddVersionKey \"FileVersion\"    \"" << m.app.version    << "\"\n";
    ts << "VIAddVersionKey \"ProductVersion\" \"" << m.app.version    << "\"\n\n";

    for (const auto &comp : m.components) {
        QString flags = comp.required ? "SectionIn RO" : "";
        ts << "Section \"" << comp.name << "\"  SEC_" << comp.id.toUpper() << "\n";
        if (!flags.isEmpty()) ts << "  " << flags << "\n";
        ts << "  SetOutPath \"$INSTDIR\"\n";
        for (const auto &fe : comp.files) {
            QString src = fe.src;
            src.replace("/", "\\");
            ts << "  File /r \"payload\\" << src << "\"\n";
        }
        ts << "SectionEnd\n\n";
    }

    // Shortcuts
    ts << "Section -Post\n";
    ts << "  WriteUninstaller \"$INSTDIR\\Uninstall.exe\"\n";
    for (const auto &sc : m.shortcuts) {
        if (sc.type == "app" || sc.type.isEmpty()) {
            ts << "  CreateShortCut \"$DESKTOP\\" << sc.name << ".lnk\" \""
               << m.resolve(sc.target, "windows").replace("/", "\\") << "\"\n";
        }
    }
    ts << "  WriteRegStr HKLM \"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\"
       << m.app.identifier << "\" \"DisplayName\" \"" << m.app.name << "\"\n";
    ts << "  WriteRegStr HKLM \"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\"
       << m.app.identifier << "\" \"UninstallString\" \"$INSTDIR\\Uninstall.exe\"\n";
    ts << "SectionEnd\n\n";

    ts << "Section \"Uninstall\"\n";
    ts << "  RMDir /r \"$INSTDIR\"\n";
    ts << "  Delete \"$DESKTOP\\" << m.app.name << ".lnk\"\n";
    ts << "  DeleteRegKey HKLM \"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\"
       << m.app.identifier << "\"\n";
    ts << "SectionEnd\n";

    return s;
}

bool WindowsBackend::compileMakensis(const QString &nsiPath, const QString &exePath) const
{
    QProcess p;
    p.start("makensis", {QString("/DOUTFILE=%1").arg(exePath), nsiPath});
    p.waitForFinished(120000);
    return p.exitCode() == 0;
}
